### ISSUE TITLE
No such export

### ISSUE THREAD

**Issue by vanemp21** [jetpnix/mb_notify#1]
Sorry if its a stupid question, its my first time using exports. Am I doing something wrong? I tried to use it in a simple item usable like bread.

`ESX.RegisterUsableItem('bread', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)

	xPlayer.removeInventoryItem('bread', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 200000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
        exports['mb_notify']:sendNotification('Te has comido un pan', {type="info", vertical="top", horizontal="right", variant="filled", duration=1000})
	--TriggerClientEvent('esx:showNotification', source, _U('used_bread'))
end)`

![image](https://user-images.githubusercontent.com/73803726/114199898-fe703080-9954-11eb-97a5-62ba41f99e60.png)

**Comment by deBBuu** [comment]
doesn't work for me too

**Comment by baguscodestudio** [comment]
have you made sure the script name is mb_notify?

**Comment by vanemp21** [comment]
of course

**Comment by baguscodestudio** [comment]
could you show me your server cfg and screenshot the script that it has been started in the server console?

**Comment by deBBuu** [comment]
![image](https://user-images.githubusercontent.com/62139065/114266356-33808f80-99f6-11eb-81ca-7848d74508ef.png)
![image](https://user-images.githubusercontent.com/62139065/114266367-42ffd880-99f6-11eb-9891-438e08e0cbb8.png)
![image](https://user-images.githubusercontent.com/62139065/114266377-4dba6d80-99f6-11eb-923f-c9f5099ddd8f.png)
![image](https://user-images.githubusercontent.com/62139065/114266439-b43f8b80-99f6-11eb-88e6-1a00fcfb0f89.png)
![image](https://user-images.githubusercontent.com/62139065/114266446-c0c3e400-99f6-11eb-8197-f7fb06aeeedf.png)

So, i Did something wrong or what?

**Comment by vanemp21** [comment]
![image](https://user-images.githubusercontent.com/73803726/114268640-6466c180-9a02-11eb-85b0-40859b33fbcd.png)
I tried add mb_notify as dependency of esx_basicneeds for try, but anyway don't work

**Comment by baguscodestudio** [comment]
For @vanemp21 i just realized that is server side, while the intend of use for the export is client side. For server side you can do `TriggerClientEvent('mb_notify:sendNotification', xPlayer.source, 'your message here', {options here})`

@deBBuu I believe that's already correct usage, can you screenshot your error?

**Comment by deBBuu** [comment]
> 
> 
> For @vanemp21 i just realized that is server side, while the intend of use for the export is client side. For server side you can do `TriggerClientEvent('mb_notify:sendNotification', xPlayer.source, 'your message here', {options here})`
> 
> @deBBuu I believe that's already correct usage, can you screenshot your error?

no errors in client console :(  
![image](https://user-images.githubusercontent.com/62139065/114269958-076f0980-9a0a-11eb-850c-ffb38bf4bfbb.png)

**Comment by baguscodestudio** [comment]
@deBBuu then it is a different issue, and should be working just fine
